// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               v7.34.1
// source: game_protocol.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "squadpuzzle";

export interface ConnectIntent {
  roomCode: string;
  sessionToken: string;
}

export interface ClaimPieceIntent {
  pieceId: string;
  clientMessageId: string;
}

export interface MovePieceIntent {
  pieceId: string;
  positionX: number;
  positionY: number;
  clientTimestamp: number;
}

export interface ReleasePieceIntent {
  pieceId: string;
  clientMessageId: string;
}

export interface HeartbeatIntent {
}

export interface ReconnectSyncIntent {
  clientMessageId: string;
}

export interface LeaveRoomIntent {
  clientMessageId: string;
}

export interface PieceLockedEvent {
  pieceId: string;
  playerSessionId: string;
  playerName: string;
  displayDisambiguator: string;
  zIndex: number;
}

export interface RoomMovementTick {
  tickId: number;
  moves: MovePieceIntent[];
}

export interface PiecePlacedEvent {
  pieceId: string;
  positionX: number;
  positionY: number;
  playerSessionId: string;
  isCorrectPosition: boolean;
  placedAt: number;
}

export interface PieceReleasedEvent {
  pieceId: string;
  positionX: number;
  positionY: number;
  releaseReason: string;
}

export interface PlayerJoinedEvent {
  playerSessionId: string;
  playerName: string;
  displayDisambiguator: string;
  playerCount: number;
}

export interface PlayerLeftEvent {
  playerSessionId: string;
  reason: string;
  gracePeriodExpiry: number;
}

export interface RoomCompletedEvent {
  solveTimeMs: number;
  completedAt: number;
}

export interface RoomExpiredEvent {
  expiredAt: number;
}

export interface RoomExpiringSoonEvent {
  expiresAt: number;
  remainingMs: number;
}

export interface ErrorEvent {
  code: string;
  message: string;
  contextPieceId: string;
}

export interface PieceState {
  pieceId: string;
  currentPositionX: number;
  currentPositionY: number;
  zIndex: number;
  placed: boolean;
  lockedBySessionId: string;
}

export interface PlayerState {
  sessionId: string;
  displayName: string;
  displayDisambiguator: string;
  connectionState: string;
}

export interface LockState {
  pieceId: string;
  lockedBySessionId: string;
  lockState: string;
}

export interface RoomStateSnapshot {
  lastEventId: number;
  gridSize: number;
  pieceCount: number;
  placedPieceCount: number;
  completed: boolean;
  solveTimeMs: number;
  baseImageUrl: string;
  maskMetadataUrl: string;
  pieces: PieceState[];
  players: PlayerState[];
  locks: LockState[];
}

export interface GameMessage {
  schemaVersion: number;
  roomId: string;
  eventId: number;
  serverTime: number;
  connectIntent?: ConnectIntent | undefined;
  claimPieceIntent?: ClaimPieceIntent | undefined;
  movePieceIntent?: MovePieceIntent | undefined;
  releasePieceIntent?: ReleasePieceIntent | undefined;
  heartbeatIntent?: HeartbeatIntent | undefined;
  reconnectSyncIntent?: ReconnectSyncIntent | undefined;
  leaveRoomIntent?: LeaveRoomIntent | undefined;
  pieceLockedEvent?: PieceLockedEvent | undefined;
  roomMovementTick?: RoomMovementTick | undefined;
  piecePlacedEvent?: PiecePlacedEvent | undefined;
  pieceReleasedEvent?: PieceReleasedEvent | undefined;
  playerJoinedEvent?: PlayerJoinedEvent | undefined;
  playerLeftEvent?: PlayerLeftEvent | undefined;
  roomCompletedEvent?: RoomCompletedEvent | undefined;
  roomExpiredEvent?: RoomExpiredEvent | undefined;
  roomExpiringSoonEvent?: RoomExpiringSoonEvent | undefined;
  errorEvent?: ErrorEvent | undefined;
  roomStateSnapshot?: RoomStateSnapshot | undefined;
}

function createBaseConnectIntent(): ConnectIntent {
  return { roomCode: "", sessionToken: "" };
}

export const ConnectIntent: MessageFns<ConnectIntent> = {
  encode(message: ConnectIntent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.roomCode !== "") {
      writer.uint32(10).string(message.roomCode);
    }
    if (message.sessionToken !== "") {
      writer.uint32(18).string(message.sessionToken);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ConnectIntent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseConnectIntent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.roomCode = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.sessionToken = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ConnectIntent {
    return {
      roomCode: isSet(object.roomCode)
        ? globalThis.String(object.roomCode)
        : isSet(object.room_code)
        ? globalThis.String(object.room_code)
        : "",
      sessionToken: isSet(object.sessionToken)
        ? globalThis.String(object.sessionToken)
        : isSet(object.session_token)
        ? globalThis.String(object.session_token)
        : "",
    };
  },

  toJSON(message: ConnectIntent): unknown {
    const obj: any = {};
    if (message.roomCode !== "") {
      obj.roomCode = message.roomCode;
    }
    if (message.sessionToken !== "") {
      obj.sessionToken = message.sessionToken;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ConnectIntent>, I>>(base?: I): ConnectIntent {
    return ConnectIntent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ConnectIntent>, I>>(object: I): ConnectIntent {
    const message = createBaseConnectIntent();
    message.roomCode = object.roomCode ?? "";
    message.sessionToken = object.sessionToken ?? "";
    return message;
  },
};

function createBaseClaimPieceIntent(): ClaimPieceIntent {
  return { pieceId: "", clientMessageId: "" };
}

export const ClaimPieceIntent: MessageFns<ClaimPieceIntent> = {
  encode(message: ClaimPieceIntent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pieceId !== "") {
      writer.uint32(10).string(message.pieceId);
    }
    if (message.clientMessageId !== "") {
      writer.uint32(18).string(message.clientMessageId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ClaimPieceIntent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseClaimPieceIntent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.pieceId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.clientMessageId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ClaimPieceIntent {
    return {
      pieceId: isSet(object.pieceId)
        ? globalThis.String(object.pieceId)
        : isSet(object.piece_id)
        ? globalThis.String(object.piece_id)
        : "",
      clientMessageId: isSet(object.clientMessageId)
        ? globalThis.String(object.clientMessageId)
        : isSet(object.client_message_id)
        ? globalThis.String(object.client_message_id)
        : "",
    };
  },

  toJSON(message: ClaimPieceIntent): unknown {
    const obj: any = {};
    if (message.pieceId !== "") {
      obj.pieceId = message.pieceId;
    }
    if (message.clientMessageId !== "") {
      obj.clientMessageId = message.clientMessageId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ClaimPieceIntent>, I>>(base?: I): ClaimPieceIntent {
    return ClaimPieceIntent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ClaimPieceIntent>, I>>(object: I): ClaimPieceIntent {
    const message = createBaseClaimPieceIntent();
    message.pieceId = object.pieceId ?? "";
    message.clientMessageId = object.clientMessageId ?? "";
    return message;
  },
};

function createBaseMovePieceIntent(): MovePieceIntent {
  return { pieceId: "", positionX: 0, positionY: 0, clientTimestamp: 0 };
}

export const MovePieceIntent: MessageFns<MovePieceIntent> = {
  encode(message: MovePieceIntent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pieceId !== "") {
      writer.uint32(10).string(message.pieceId);
    }
    if (message.positionX !== 0) {
      writer.uint32(16).sint32(message.positionX);
    }
    if (message.positionY !== 0) {
      writer.uint32(24).sint32(message.positionY);
    }
    if (message.clientTimestamp !== 0) {
      writer.uint32(32).uint64(message.clientTimestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MovePieceIntent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMovePieceIntent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.pieceId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.positionX = reader.sint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.positionY = reader.sint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.clientTimestamp = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MovePieceIntent {
    return {
      pieceId: isSet(object.pieceId)
        ? globalThis.String(object.pieceId)
        : isSet(object.piece_id)
        ? globalThis.String(object.piece_id)
        : "",
      positionX: isSet(object.positionX)
        ? globalThis.Number(object.positionX)
        : isSet(object.position_x)
        ? globalThis.Number(object.position_x)
        : 0,
      positionY: isSet(object.positionY)
        ? globalThis.Number(object.positionY)
        : isSet(object.position_y)
        ? globalThis.Number(object.position_y)
        : 0,
      clientTimestamp: isSet(object.clientTimestamp)
        ? globalThis.Number(object.clientTimestamp)
        : isSet(object.client_timestamp)
        ? globalThis.Number(object.client_timestamp)
        : 0,
    };
  },

  toJSON(message: MovePieceIntent): unknown {
    const obj: any = {};
    if (message.pieceId !== "") {
      obj.pieceId = message.pieceId;
    }
    if (message.positionX !== 0) {
      obj.positionX = Math.round(message.positionX);
    }
    if (message.positionY !== 0) {
      obj.positionY = Math.round(message.positionY);
    }
    if (message.clientTimestamp !== 0) {
      obj.clientTimestamp = Math.round(message.clientTimestamp);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MovePieceIntent>, I>>(base?: I): MovePieceIntent {
    return MovePieceIntent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MovePieceIntent>, I>>(object: I): MovePieceIntent {
    const message = createBaseMovePieceIntent();
    message.pieceId = object.pieceId ?? "";
    message.positionX = object.positionX ?? 0;
    message.positionY = object.positionY ?? 0;
    message.clientTimestamp = object.clientTimestamp ?? 0;
    return message;
  },
};

function createBaseReleasePieceIntent(): ReleasePieceIntent {
  return { pieceId: "", clientMessageId: "" };
}

export const ReleasePieceIntent: MessageFns<ReleasePieceIntent> = {
  encode(message: ReleasePieceIntent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pieceId !== "") {
      writer.uint32(10).string(message.pieceId);
    }
    if (message.clientMessageId !== "") {
      writer.uint32(18).string(message.clientMessageId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ReleasePieceIntent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReleasePieceIntent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.pieceId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.clientMessageId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ReleasePieceIntent {
    return {
      pieceId: isSet(object.pieceId)
        ? globalThis.String(object.pieceId)
        : isSet(object.piece_id)
        ? globalThis.String(object.piece_id)
        : "",
      clientMessageId: isSet(object.clientMessageId)
        ? globalThis.String(object.clientMessageId)
        : isSet(object.client_message_id)
        ? globalThis.String(object.client_message_id)
        : "",
    };
  },

  toJSON(message: ReleasePieceIntent): unknown {
    const obj: any = {};
    if (message.pieceId !== "") {
      obj.pieceId = message.pieceId;
    }
    if (message.clientMessageId !== "") {
      obj.clientMessageId = message.clientMessageId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ReleasePieceIntent>, I>>(base?: I): ReleasePieceIntent {
    return ReleasePieceIntent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReleasePieceIntent>, I>>(object: I): ReleasePieceIntent {
    const message = createBaseReleasePieceIntent();
    message.pieceId = object.pieceId ?? "";
    message.clientMessageId = object.clientMessageId ?? "";
    return message;
  },
};

function createBaseHeartbeatIntent(): HeartbeatIntent {
  return {};
}

export const HeartbeatIntent: MessageFns<HeartbeatIntent> = {
  encode(_: HeartbeatIntent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HeartbeatIntent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHeartbeatIntent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): HeartbeatIntent {
    return {};
  },

  toJSON(_: HeartbeatIntent): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<HeartbeatIntent>, I>>(base?: I): HeartbeatIntent {
    return HeartbeatIntent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HeartbeatIntent>, I>>(_: I): HeartbeatIntent {
    const message = createBaseHeartbeatIntent();
    return message;
  },
};

function createBaseReconnectSyncIntent(): ReconnectSyncIntent {
  return { clientMessageId: "" };
}

export const ReconnectSyncIntent: MessageFns<ReconnectSyncIntent> = {
  encode(message: ReconnectSyncIntent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.clientMessageId !== "") {
      writer.uint32(10).string(message.clientMessageId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ReconnectSyncIntent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReconnectSyncIntent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.clientMessageId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ReconnectSyncIntent {
    return {
      clientMessageId: isSet(object.clientMessageId)
        ? globalThis.String(object.clientMessageId)
        : isSet(object.client_message_id)
        ? globalThis.String(object.client_message_id)
        : "",
    };
  },

  toJSON(message: ReconnectSyncIntent): unknown {
    const obj: any = {};
    if (message.clientMessageId !== "") {
      obj.clientMessageId = message.clientMessageId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ReconnectSyncIntent>, I>>(base?: I): ReconnectSyncIntent {
    return ReconnectSyncIntent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReconnectSyncIntent>, I>>(object: I): ReconnectSyncIntent {
    const message = createBaseReconnectSyncIntent();
    message.clientMessageId = object.clientMessageId ?? "";
    return message;
  },
};

function createBaseLeaveRoomIntent(): LeaveRoomIntent {
  return { clientMessageId: "" };
}

export const LeaveRoomIntent: MessageFns<LeaveRoomIntent> = {
  encode(message: LeaveRoomIntent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.clientMessageId !== "") {
      writer.uint32(10).string(message.clientMessageId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LeaveRoomIntent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLeaveRoomIntent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.clientMessageId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LeaveRoomIntent {
    return {
      clientMessageId: isSet(object.clientMessageId)
        ? globalThis.String(object.clientMessageId)
        : isSet(object.client_message_id)
        ? globalThis.String(object.client_message_id)
        : "",
    };
  },

  toJSON(message: LeaveRoomIntent): unknown {
    const obj: any = {};
    if (message.clientMessageId !== "") {
      obj.clientMessageId = message.clientMessageId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LeaveRoomIntent>, I>>(base?: I): LeaveRoomIntent {
    return LeaveRoomIntent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LeaveRoomIntent>, I>>(object: I): LeaveRoomIntent {
    const message = createBaseLeaveRoomIntent();
    message.clientMessageId = object.clientMessageId ?? "";
    return message;
  },
};

function createBasePieceLockedEvent(): PieceLockedEvent {
  return { pieceId: "", playerSessionId: "", playerName: "", displayDisambiguator: "", zIndex: 0 };
}

export const PieceLockedEvent: MessageFns<PieceLockedEvent> = {
  encode(message: PieceLockedEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pieceId !== "") {
      writer.uint32(10).string(message.pieceId);
    }
    if (message.playerSessionId !== "") {
      writer.uint32(18).string(message.playerSessionId);
    }
    if (message.playerName !== "") {
      writer.uint32(26).string(message.playerName);
    }
    if (message.displayDisambiguator !== "") {
      writer.uint32(34).string(message.displayDisambiguator);
    }
    if (message.zIndex !== 0) {
      writer.uint32(40).uint32(message.zIndex);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PieceLockedEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePieceLockedEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.pieceId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.playerSessionId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.playerName = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.displayDisambiguator = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.zIndex = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PieceLockedEvent {
    return {
      pieceId: isSet(object.pieceId)
        ? globalThis.String(object.pieceId)
        : isSet(object.piece_id)
        ? globalThis.String(object.piece_id)
        : "",
      playerSessionId: isSet(object.playerSessionId)
        ? globalThis.String(object.playerSessionId)
        : isSet(object.player_session_id)
        ? globalThis.String(object.player_session_id)
        : "",
      playerName: isSet(object.playerName)
        ? globalThis.String(object.playerName)
        : isSet(object.player_name)
        ? globalThis.String(object.player_name)
        : "",
      displayDisambiguator: isSet(object.displayDisambiguator)
        ? globalThis.String(object.displayDisambiguator)
        : isSet(object.display_disambiguator)
        ? globalThis.String(object.display_disambiguator)
        : "",
      zIndex: isSet(object.zIndex)
        ? globalThis.Number(object.zIndex)
        : isSet(object.z_index)
        ? globalThis.Number(object.z_index)
        : 0,
    };
  },

  toJSON(message: PieceLockedEvent): unknown {
    const obj: any = {};
    if (message.pieceId !== "") {
      obj.pieceId = message.pieceId;
    }
    if (message.playerSessionId !== "") {
      obj.playerSessionId = message.playerSessionId;
    }
    if (message.playerName !== "") {
      obj.playerName = message.playerName;
    }
    if (message.displayDisambiguator !== "") {
      obj.displayDisambiguator = message.displayDisambiguator;
    }
    if (message.zIndex !== 0) {
      obj.zIndex = Math.round(message.zIndex);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PieceLockedEvent>, I>>(base?: I): PieceLockedEvent {
    return PieceLockedEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PieceLockedEvent>, I>>(object: I): PieceLockedEvent {
    const message = createBasePieceLockedEvent();
    message.pieceId = object.pieceId ?? "";
    message.playerSessionId = object.playerSessionId ?? "";
    message.playerName = object.playerName ?? "";
    message.displayDisambiguator = object.displayDisambiguator ?? "";
    message.zIndex = object.zIndex ?? 0;
    return message;
  },
};

function createBaseRoomMovementTick(): RoomMovementTick {
  return { tickId: 0, moves: [] };
}

export const RoomMovementTick: MessageFns<RoomMovementTick> = {
  encode(message: RoomMovementTick, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tickId !== 0) {
      writer.uint32(8).uint64(message.tickId);
    }
    for (const v of message.moves) {
      MovePieceIntent.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RoomMovementTick {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRoomMovementTick();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.tickId = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.moves.push(MovePieceIntent.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RoomMovementTick {
    return {
      tickId: isSet(object.tickId)
        ? globalThis.Number(object.tickId)
        : isSet(object.tick_id)
        ? globalThis.Number(object.tick_id)
        : 0,
      moves: globalThis.Array.isArray(object?.moves) ? object.moves.map((e: any) => MovePieceIntent.fromJSON(e)) : [],
    };
  },

  toJSON(message: RoomMovementTick): unknown {
    const obj: any = {};
    if (message.tickId !== 0) {
      obj.tickId = Math.round(message.tickId);
    }
    if (message.moves?.length) {
      obj.moves = message.moves.map((e) => MovePieceIntent.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RoomMovementTick>, I>>(base?: I): RoomMovementTick {
    return RoomMovementTick.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RoomMovementTick>, I>>(object: I): RoomMovementTick {
    const message = createBaseRoomMovementTick();
    message.tickId = object.tickId ?? 0;
    message.moves = object.moves?.map((e) => MovePieceIntent.fromPartial(e)) || [];
    return message;
  },
};

function createBasePiecePlacedEvent(): PiecePlacedEvent {
  return { pieceId: "", positionX: 0, positionY: 0, playerSessionId: "", isCorrectPosition: false, placedAt: 0 };
}

export const PiecePlacedEvent: MessageFns<PiecePlacedEvent> = {
  encode(message: PiecePlacedEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pieceId !== "") {
      writer.uint32(10).string(message.pieceId);
    }
    if (message.positionX !== 0) {
      writer.uint32(16).sint32(message.positionX);
    }
    if (message.positionY !== 0) {
      writer.uint32(24).sint32(message.positionY);
    }
    if (message.playerSessionId !== "") {
      writer.uint32(34).string(message.playerSessionId);
    }
    if (message.isCorrectPosition !== false) {
      writer.uint32(40).bool(message.isCorrectPosition);
    }
    if (message.placedAt !== 0) {
      writer.uint32(48).uint64(message.placedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PiecePlacedEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePiecePlacedEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.pieceId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.positionX = reader.sint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.positionY = reader.sint32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.playerSessionId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.isCorrectPosition = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.placedAt = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PiecePlacedEvent {
    return {
      pieceId: isSet(object.pieceId)
        ? globalThis.String(object.pieceId)
        : isSet(object.piece_id)
        ? globalThis.String(object.piece_id)
        : "",
      positionX: isSet(object.positionX)
        ? globalThis.Number(object.positionX)
        : isSet(object.position_x)
        ? globalThis.Number(object.position_x)
        : 0,
      positionY: isSet(object.positionY)
        ? globalThis.Number(object.positionY)
        : isSet(object.position_y)
        ? globalThis.Number(object.position_y)
        : 0,
      playerSessionId: isSet(object.playerSessionId)
        ? globalThis.String(object.playerSessionId)
        : isSet(object.player_session_id)
        ? globalThis.String(object.player_session_id)
        : "",
      isCorrectPosition: isSet(object.isCorrectPosition)
        ? globalThis.Boolean(object.isCorrectPosition)
        : isSet(object.is_correct_position)
        ? globalThis.Boolean(object.is_correct_position)
        : false,
      placedAt: isSet(object.placedAt)
        ? globalThis.Number(object.placedAt)
        : isSet(object.placed_at)
        ? globalThis.Number(object.placed_at)
        : 0,
    };
  },

  toJSON(message: PiecePlacedEvent): unknown {
    const obj: any = {};
    if (message.pieceId !== "") {
      obj.pieceId = message.pieceId;
    }
    if (message.positionX !== 0) {
      obj.positionX = Math.round(message.positionX);
    }
    if (message.positionY !== 0) {
      obj.positionY = Math.round(message.positionY);
    }
    if (message.playerSessionId !== "") {
      obj.playerSessionId = message.playerSessionId;
    }
    if (message.isCorrectPosition !== false) {
      obj.isCorrectPosition = message.isCorrectPosition;
    }
    if (message.placedAt !== 0) {
      obj.placedAt = Math.round(message.placedAt);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PiecePlacedEvent>, I>>(base?: I): PiecePlacedEvent {
    return PiecePlacedEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PiecePlacedEvent>, I>>(object: I): PiecePlacedEvent {
    const message = createBasePiecePlacedEvent();
    message.pieceId = object.pieceId ?? "";
    message.positionX = object.positionX ?? 0;
    message.positionY = object.positionY ?? 0;
    message.playerSessionId = object.playerSessionId ?? "";
    message.isCorrectPosition = object.isCorrectPosition ?? false;
    message.placedAt = object.placedAt ?? 0;
    return message;
  },
};

function createBasePieceReleasedEvent(): PieceReleasedEvent {
  return { pieceId: "", positionX: 0, positionY: 0, releaseReason: "" };
}

export const PieceReleasedEvent: MessageFns<PieceReleasedEvent> = {
  encode(message: PieceReleasedEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pieceId !== "") {
      writer.uint32(10).string(message.pieceId);
    }
    if (message.positionX !== 0) {
      writer.uint32(16).sint32(message.positionX);
    }
    if (message.positionY !== 0) {
      writer.uint32(24).sint32(message.positionY);
    }
    if (message.releaseReason !== "") {
      writer.uint32(34).string(message.releaseReason);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PieceReleasedEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePieceReleasedEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.pieceId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.positionX = reader.sint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.positionY = reader.sint32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.releaseReason = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PieceReleasedEvent {
    return {
      pieceId: isSet(object.pieceId)
        ? globalThis.String(object.pieceId)
        : isSet(object.piece_id)
        ? globalThis.String(object.piece_id)
        : "",
      positionX: isSet(object.positionX)
        ? globalThis.Number(object.positionX)
        : isSet(object.position_x)
        ? globalThis.Number(object.position_x)
        : 0,
      positionY: isSet(object.positionY)
        ? globalThis.Number(object.positionY)
        : isSet(object.position_y)
        ? globalThis.Number(object.position_y)
        : 0,
      releaseReason: isSet(object.releaseReason)
        ? globalThis.String(object.releaseReason)
        : isSet(object.release_reason)
        ? globalThis.String(object.release_reason)
        : "",
    };
  },

  toJSON(message: PieceReleasedEvent): unknown {
    const obj: any = {};
    if (message.pieceId !== "") {
      obj.pieceId = message.pieceId;
    }
    if (message.positionX !== 0) {
      obj.positionX = Math.round(message.positionX);
    }
    if (message.positionY !== 0) {
      obj.positionY = Math.round(message.positionY);
    }
    if (message.releaseReason !== "") {
      obj.releaseReason = message.releaseReason;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PieceReleasedEvent>, I>>(base?: I): PieceReleasedEvent {
    return PieceReleasedEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PieceReleasedEvent>, I>>(object: I): PieceReleasedEvent {
    const message = createBasePieceReleasedEvent();
    message.pieceId = object.pieceId ?? "";
    message.positionX = object.positionX ?? 0;
    message.positionY = object.positionY ?? 0;
    message.releaseReason = object.releaseReason ?? "";
    return message;
  },
};

function createBasePlayerJoinedEvent(): PlayerJoinedEvent {
  return { playerSessionId: "", playerName: "", displayDisambiguator: "", playerCount: 0 };
}

export const PlayerJoinedEvent: MessageFns<PlayerJoinedEvent> = {
  encode(message: PlayerJoinedEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.playerSessionId !== "") {
      writer.uint32(10).string(message.playerSessionId);
    }
    if (message.playerName !== "") {
      writer.uint32(18).string(message.playerName);
    }
    if (message.displayDisambiguator !== "") {
      writer.uint32(26).string(message.displayDisambiguator);
    }
    if (message.playerCount !== 0) {
      writer.uint32(32).uint32(message.playerCount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PlayerJoinedEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePlayerJoinedEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.playerSessionId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.playerName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.displayDisambiguator = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.playerCount = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PlayerJoinedEvent {
    return {
      playerSessionId: isSet(object.playerSessionId)
        ? globalThis.String(object.playerSessionId)
        : isSet(object.player_session_id)
        ? globalThis.String(object.player_session_id)
        : "",
      playerName: isSet(object.playerName)
        ? globalThis.String(object.playerName)
        : isSet(object.player_name)
        ? globalThis.String(object.player_name)
        : "",
      displayDisambiguator: isSet(object.displayDisambiguator)
        ? globalThis.String(object.displayDisambiguator)
        : isSet(object.display_disambiguator)
        ? globalThis.String(object.display_disambiguator)
        : "",
      playerCount: isSet(object.playerCount)
        ? globalThis.Number(object.playerCount)
        : isSet(object.player_count)
        ? globalThis.Number(object.player_count)
        : 0,
    };
  },

  toJSON(message: PlayerJoinedEvent): unknown {
    const obj: any = {};
    if (message.playerSessionId !== "") {
      obj.playerSessionId = message.playerSessionId;
    }
    if (message.playerName !== "") {
      obj.playerName = message.playerName;
    }
    if (message.displayDisambiguator !== "") {
      obj.displayDisambiguator = message.displayDisambiguator;
    }
    if (message.playerCount !== 0) {
      obj.playerCount = Math.round(message.playerCount);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PlayerJoinedEvent>, I>>(base?: I): PlayerJoinedEvent {
    return PlayerJoinedEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PlayerJoinedEvent>, I>>(object: I): PlayerJoinedEvent {
    const message = createBasePlayerJoinedEvent();
    message.playerSessionId = object.playerSessionId ?? "";
    message.playerName = object.playerName ?? "";
    message.displayDisambiguator = object.displayDisambiguator ?? "";
    message.playerCount = object.playerCount ?? 0;
    return message;
  },
};

function createBasePlayerLeftEvent(): PlayerLeftEvent {
  return { playerSessionId: "", reason: "", gracePeriodExpiry: 0 };
}

export const PlayerLeftEvent: MessageFns<PlayerLeftEvent> = {
  encode(message: PlayerLeftEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.playerSessionId !== "") {
      writer.uint32(10).string(message.playerSessionId);
    }
    if (message.reason !== "") {
      writer.uint32(18).string(message.reason);
    }
    if (message.gracePeriodExpiry !== 0) {
      writer.uint32(24).uint64(message.gracePeriodExpiry);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PlayerLeftEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePlayerLeftEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.playerSessionId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.reason = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.gracePeriodExpiry = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PlayerLeftEvent {
    return {
      playerSessionId: isSet(object.playerSessionId)
        ? globalThis.String(object.playerSessionId)
        : isSet(object.player_session_id)
        ? globalThis.String(object.player_session_id)
        : "",
      reason: isSet(object.reason) ? globalThis.String(object.reason) : "",
      gracePeriodExpiry: isSet(object.gracePeriodExpiry)
        ? globalThis.Number(object.gracePeriodExpiry)
        : isSet(object.grace_period_expiry)
        ? globalThis.Number(object.grace_period_expiry)
        : 0,
    };
  },

  toJSON(message: PlayerLeftEvent): unknown {
    const obj: any = {};
    if (message.playerSessionId !== "") {
      obj.playerSessionId = message.playerSessionId;
    }
    if (message.reason !== "") {
      obj.reason = message.reason;
    }
    if (message.gracePeriodExpiry !== 0) {
      obj.gracePeriodExpiry = Math.round(message.gracePeriodExpiry);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PlayerLeftEvent>, I>>(base?: I): PlayerLeftEvent {
    return PlayerLeftEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PlayerLeftEvent>, I>>(object: I): PlayerLeftEvent {
    const message = createBasePlayerLeftEvent();
    message.playerSessionId = object.playerSessionId ?? "";
    message.reason = object.reason ?? "";
    message.gracePeriodExpiry = object.gracePeriodExpiry ?? 0;
    return message;
  },
};

function createBaseRoomCompletedEvent(): RoomCompletedEvent {
  return { solveTimeMs: 0, completedAt: 0 };
}

export const RoomCompletedEvent: MessageFns<RoomCompletedEvent> = {
  encode(message: RoomCompletedEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.solveTimeMs !== 0) {
      writer.uint32(8).uint64(message.solveTimeMs);
    }
    if (message.completedAt !== 0) {
      writer.uint32(16).uint64(message.completedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RoomCompletedEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRoomCompletedEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.solveTimeMs = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.completedAt = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RoomCompletedEvent {
    return {
      solveTimeMs: isSet(object.solveTimeMs)
        ? globalThis.Number(object.solveTimeMs)
        : isSet(object.solve_time_ms)
        ? globalThis.Number(object.solve_time_ms)
        : 0,
      completedAt: isSet(object.completedAt)
        ? globalThis.Number(object.completedAt)
        : isSet(object.completed_at)
        ? globalThis.Number(object.completed_at)
        : 0,
    };
  },

  toJSON(message: RoomCompletedEvent): unknown {
    const obj: any = {};
    if (message.solveTimeMs !== 0) {
      obj.solveTimeMs = Math.round(message.solveTimeMs);
    }
    if (message.completedAt !== 0) {
      obj.completedAt = Math.round(message.completedAt);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RoomCompletedEvent>, I>>(base?: I): RoomCompletedEvent {
    return RoomCompletedEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RoomCompletedEvent>, I>>(object: I): RoomCompletedEvent {
    const message = createBaseRoomCompletedEvent();
    message.solveTimeMs = object.solveTimeMs ?? 0;
    message.completedAt = object.completedAt ?? 0;
    return message;
  },
};

function createBaseRoomExpiredEvent(): RoomExpiredEvent {
  return { expiredAt: 0 };
}

export const RoomExpiredEvent: MessageFns<RoomExpiredEvent> = {
  encode(message: RoomExpiredEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.expiredAt !== 0) {
      writer.uint32(8).uint64(message.expiredAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RoomExpiredEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRoomExpiredEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.expiredAt = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RoomExpiredEvent {
    return {
      expiredAt: isSet(object.expiredAt)
        ? globalThis.Number(object.expiredAt)
        : isSet(object.expired_at)
        ? globalThis.Number(object.expired_at)
        : 0,
    };
  },

  toJSON(message: RoomExpiredEvent): unknown {
    const obj: any = {};
    if (message.expiredAt !== 0) {
      obj.expiredAt = Math.round(message.expiredAt);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RoomExpiredEvent>, I>>(base?: I): RoomExpiredEvent {
    return RoomExpiredEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RoomExpiredEvent>, I>>(object: I): RoomExpiredEvent {
    const message = createBaseRoomExpiredEvent();
    message.expiredAt = object.expiredAt ?? 0;
    return message;
  },
};

function createBaseRoomExpiringSoonEvent(): RoomExpiringSoonEvent {
  return { expiresAt: 0, remainingMs: 0 };
}

export const RoomExpiringSoonEvent: MessageFns<RoomExpiringSoonEvent> = {
  encode(message: RoomExpiringSoonEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.expiresAt !== 0) {
      writer.uint32(8).uint64(message.expiresAt);
    }
    if (message.remainingMs !== 0) {
      writer.uint32(16).uint64(message.remainingMs);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RoomExpiringSoonEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRoomExpiringSoonEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.expiresAt = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.remainingMs = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RoomExpiringSoonEvent {
    return {
      expiresAt: isSet(object.expiresAt)
        ? globalThis.Number(object.expiresAt)
        : isSet(object.expires_at)
        ? globalThis.Number(object.expires_at)
        : 0,
      remainingMs: isSet(object.remainingMs)
        ? globalThis.Number(object.remainingMs)
        : isSet(object.remaining_ms)
        ? globalThis.Number(object.remaining_ms)
        : 0,
    };
  },

  toJSON(message: RoomExpiringSoonEvent): unknown {
    const obj: any = {};
    if (message.expiresAt !== 0) {
      obj.expiresAt = Math.round(message.expiresAt);
    }
    if (message.remainingMs !== 0) {
      obj.remainingMs = Math.round(message.remainingMs);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RoomExpiringSoonEvent>, I>>(base?: I): RoomExpiringSoonEvent {
    return RoomExpiringSoonEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RoomExpiringSoonEvent>, I>>(object: I): RoomExpiringSoonEvent {
    const message = createBaseRoomExpiringSoonEvent();
    message.expiresAt = object.expiresAt ?? 0;
    message.remainingMs = object.remainingMs ?? 0;
    return message;
  },
};

function createBaseErrorEvent(): ErrorEvent {
  return { code: "", message: "", contextPieceId: "" };
}

export const ErrorEvent: MessageFns<ErrorEvent> = {
  encode(message: ErrorEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.code !== "") {
      writer.uint32(10).string(message.code);
    }
    if (message.message !== "") {
      writer.uint32(18).string(message.message);
    }
    if (message.contextPieceId !== "") {
      writer.uint32(26).string(message.contextPieceId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ErrorEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseErrorEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.code = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.contextPieceId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ErrorEvent {
    return {
      code: isSet(object.code) ? globalThis.String(object.code) : "",
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      contextPieceId: isSet(object.contextPieceId)
        ? globalThis.String(object.contextPieceId)
        : isSet(object.context_piece_id)
        ? globalThis.String(object.context_piece_id)
        : "",
    };
  },

  toJSON(message: ErrorEvent): unknown {
    const obj: any = {};
    if (message.code !== "") {
      obj.code = message.code;
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.contextPieceId !== "") {
      obj.contextPieceId = message.contextPieceId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ErrorEvent>, I>>(base?: I): ErrorEvent {
    return ErrorEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ErrorEvent>, I>>(object: I): ErrorEvent {
    const message = createBaseErrorEvent();
    message.code = object.code ?? "";
    message.message = object.message ?? "";
    message.contextPieceId = object.contextPieceId ?? "";
    return message;
  },
};

function createBasePieceState(): PieceState {
  return { pieceId: "", currentPositionX: 0, currentPositionY: 0, zIndex: 0, placed: false, lockedBySessionId: "" };
}

export const PieceState: MessageFns<PieceState> = {
  encode(message: PieceState, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pieceId !== "") {
      writer.uint32(10).string(message.pieceId);
    }
    if (message.currentPositionX !== 0) {
      writer.uint32(16).sint32(message.currentPositionX);
    }
    if (message.currentPositionY !== 0) {
      writer.uint32(24).sint32(message.currentPositionY);
    }
    if (message.zIndex !== 0) {
      writer.uint32(32).uint32(message.zIndex);
    }
    if (message.placed !== false) {
      writer.uint32(40).bool(message.placed);
    }
    if (message.lockedBySessionId !== "") {
      writer.uint32(50).string(message.lockedBySessionId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PieceState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePieceState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.pieceId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.currentPositionX = reader.sint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.currentPositionY = reader.sint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.zIndex = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.placed = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.lockedBySessionId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PieceState {
    return {
      pieceId: isSet(object.pieceId)
        ? globalThis.String(object.pieceId)
        : isSet(object.piece_id)
        ? globalThis.String(object.piece_id)
        : "",
      currentPositionX: isSet(object.currentPositionX)
        ? globalThis.Number(object.currentPositionX)
        : isSet(object.current_position_x)
        ? globalThis.Number(object.current_position_x)
        : 0,
      currentPositionY: isSet(object.currentPositionY)
        ? globalThis.Number(object.currentPositionY)
        : isSet(object.current_position_y)
        ? globalThis.Number(object.current_position_y)
        : 0,
      zIndex: isSet(object.zIndex)
        ? globalThis.Number(object.zIndex)
        : isSet(object.z_index)
        ? globalThis.Number(object.z_index)
        : 0,
      placed: isSet(object.placed) ? globalThis.Boolean(object.placed) : false,
      lockedBySessionId: isSet(object.lockedBySessionId)
        ? globalThis.String(object.lockedBySessionId)
        : isSet(object.locked_by_session_id)
        ? globalThis.String(object.locked_by_session_id)
        : "",
    };
  },

  toJSON(message: PieceState): unknown {
    const obj: any = {};
    if (message.pieceId !== "") {
      obj.pieceId = message.pieceId;
    }
    if (message.currentPositionX !== 0) {
      obj.currentPositionX = Math.round(message.currentPositionX);
    }
    if (message.currentPositionY !== 0) {
      obj.currentPositionY = Math.round(message.currentPositionY);
    }
    if (message.zIndex !== 0) {
      obj.zIndex = Math.round(message.zIndex);
    }
    if (message.placed !== false) {
      obj.placed = message.placed;
    }
    if (message.lockedBySessionId !== "") {
      obj.lockedBySessionId = message.lockedBySessionId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PieceState>, I>>(base?: I): PieceState {
    return PieceState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PieceState>, I>>(object: I): PieceState {
    const message = createBasePieceState();
    message.pieceId = object.pieceId ?? "";
    message.currentPositionX = object.currentPositionX ?? 0;
    message.currentPositionY = object.currentPositionY ?? 0;
    message.zIndex = object.zIndex ?? 0;
    message.placed = object.placed ?? false;
    message.lockedBySessionId = object.lockedBySessionId ?? "";
    return message;
  },
};

function createBasePlayerState(): PlayerState {
  return { sessionId: "", displayName: "", displayDisambiguator: "", connectionState: "" };
}

export const PlayerState: MessageFns<PlayerState> = {
  encode(message: PlayerState, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sessionId !== "") {
      writer.uint32(10).string(message.sessionId);
    }
    if (message.displayName !== "") {
      writer.uint32(18).string(message.displayName);
    }
    if (message.displayDisambiguator !== "") {
      writer.uint32(26).string(message.displayDisambiguator);
    }
    if (message.connectionState !== "") {
      writer.uint32(34).string(message.connectionState);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PlayerState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePlayerState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sessionId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.displayName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.displayDisambiguator = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.connectionState = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PlayerState {
    return {
      sessionId: isSet(object.sessionId)
        ? globalThis.String(object.sessionId)
        : isSet(object.session_id)
        ? globalThis.String(object.session_id)
        : "",
      displayName: isSet(object.displayName)
        ? globalThis.String(object.displayName)
        : isSet(object.display_name)
        ? globalThis.String(object.display_name)
        : "",
      displayDisambiguator: isSet(object.displayDisambiguator)
        ? globalThis.String(object.displayDisambiguator)
        : isSet(object.display_disambiguator)
        ? globalThis.String(object.display_disambiguator)
        : "",
      connectionState: isSet(object.connectionState)
        ? globalThis.String(object.connectionState)
        : isSet(object.connection_state)
        ? globalThis.String(object.connection_state)
        : "",
    };
  },

  toJSON(message: PlayerState): unknown {
    const obj: any = {};
    if (message.sessionId !== "") {
      obj.sessionId = message.sessionId;
    }
    if (message.displayName !== "") {
      obj.displayName = message.displayName;
    }
    if (message.displayDisambiguator !== "") {
      obj.displayDisambiguator = message.displayDisambiguator;
    }
    if (message.connectionState !== "") {
      obj.connectionState = message.connectionState;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PlayerState>, I>>(base?: I): PlayerState {
    return PlayerState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PlayerState>, I>>(object: I): PlayerState {
    const message = createBasePlayerState();
    message.sessionId = object.sessionId ?? "";
    message.displayName = object.displayName ?? "";
    message.displayDisambiguator = object.displayDisambiguator ?? "";
    message.connectionState = object.connectionState ?? "";
    return message;
  },
};

function createBaseLockState(): LockState {
  return { pieceId: "", lockedBySessionId: "", lockState: "" };
}

export const LockState: MessageFns<LockState> = {
  encode(message: LockState, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pieceId !== "") {
      writer.uint32(10).string(message.pieceId);
    }
    if (message.lockedBySessionId !== "") {
      writer.uint32(18).string(message.lockedBySessionId);
    }
    if (message.lockState !== "") {
      writer.uint32(26).string(message.lockState);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LockState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLockState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.pieceId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.lockedBySessionId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.lockState = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LockState {
    return {
      pieceId: isSet(object.pieceId)
        ? globalThis.String(object.pieceId)
        : isSet(object.piece_id)
        ? globalThis.String(object.piece_id)
        : "",
      lockedBySessionId: isSet(object.lockedBySessionId)
        ? globalThis.String(object.lockedBySessionId)
        : isSet(object.locked_by_session_id)
        ? globalThis.String(object.locked_by_session_id)
        : "",
      lockState: isSet(object.lockState)
        ? globalThis.String(object.lockState)
        : isSet(object.lock_state)
        ? globalThis.String(object.lock_state)
        : "",
    };
  },

  toJSON(message: LockState): unknown {
    const obj: any = {};
    if (message.pieceId !== "") {
      obj.pieceId = message.pieceId;
    }
    if (message.lockedBySessionId !== "") {
      obj.lockedBySessionId = message.lockedBySessionId;
    }
    if (message.lockState !== "") {
      obj.lockState = message.lockState;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LockState>, I>>(base?: I): LockState {
    return LockState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LockState>, I>>(object: I): LockState {
    const message = createBaseLockState();
    message.pieceId = object.pieceId ?? "";
    message.lockedBySessionId = object.lockedBySessionId ?? "";
    message.lockState = object.lockState ?? "";
    return message;
  },
};

function createBaseRoomStateSnapshot(): RoomStateSnapshot {
  return {
    lastEventId: 0,
    gridSize: 0,
    pieceCount: 0,
    placedPieceCount: 0,
    completed: false,
    solveTimeMs: 0,
    baseImageUrl: "",
    maskMetadataUrl: "",
    pieces: [],
    players: [],
    locks: [],
  };
}

export const RoomStateSnapshot: MessageFns<RoomStateSnapshot> = {
  encode(message: RoomStateSnapshot, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.lastEventId !== 0) {
      writer.uint32(8).uint64(message.lastEventId);
    }
    if (message.gridSize !== 0) {
      writer.uint32(16).uint32(message.gridSize);
    }
    if (message.pieceCount !== 0) {
      writer.uint32(24).uint32(message.pieceCount);
    }
    if (message.placedPieceCount !== 0) {
      writer.uint32(32).uint32(message.placedPieceCount);
    }
    if (message.completed !== false) {
      writer.uint32(40).bool(message.completed);
    }
    if (message.solveTimeMs !== 0) {
      writer.uint32(48).uint64(message.solveTimeMs);
    }
    if (message.baseImageUrl !== "") {
      writer.uint32(58).string(message.baseImageUrl);
    }
    if (message.maskMetadataUrl !== "") {
      writer.uint32(66).string(message.maskMetadataUrl);
    }
    for (const v of message.pieces) {
      PieceState.encode(v!, writer.uint32(74).fork()).join();
    }
    for (const v of message.players) {
      PlayerState.encode(v!, writer.uint32(82).fork()).join();
    }
    for (const v of message.locks) {
      LockState.encode(v!, writer.uint32(90).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RoomStateSnapshot {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRoomStateSnapshot();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.lastEventId = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.gridSize = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.pieceCount = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.placedPieceCount = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.completed = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.solveTimeMs = longToNumber(reader.uint64());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.baseImageUrl = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.maskMetadataUrl = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.pieces.push(PieceState.decode(reader, reader.uint32()));
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.players.push(PlayerState.decode(reader, reader.uint32()));
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.locks.push(LockState.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RoomStateSnapshot {
    return {
      lastEventId: isSet(object.lastEventId)
        ? globalThis.Number(object.lastEventId)
        : isSet(object.last_event_id)
        ? globalThis.Number(object.last_event_id)
        : 0,
      gridSize: isSet(object.gridSize)
        ? globalThis.Number(object.gridSize)
        : isSet(object.grid_size)
        ? globalThis.Number(object.grid_size)
        : 0,
      pieceCount: isSet(object.pieceCount)
        ? globalThis.Number(object.pieceCount)
        : isSet(object.piece_count)
        ? globalThis.Number(object.piece_count)
        : 0,
      placedPieceCount: isSet(object.placedPieceCount)
        ? globalThis.Number(object.placedPieceCount)
        : isSet(object.placed_piece_count)
        ? globalThis.Number(object.placed_piece_count)
        : 0,
      completed: isSet(object.completed) ? globalThis.Boolean(object.completed) : false,
      solveTimeMs: isSet(object.solveTimeMs)
        ? globalThis.Number(object.solveTimeMs)
        : isSet(object.solve_time_ms)
        ? globalThis.Number(object.solve_time_ms)
        : 0,
      baseImageUrl: isSet(object.baseImageUrl)
        ? globalThis.String(object.baseImageUrl)
        : isSet(object.base_image_url)
        ? globalThis.String(object.base_image_url)
        : "",
      maskMetadataUrl: isSet(object.maskMetadataUrl)
        ? globalThis.String(object.maskMetadataUrl)
        : isSet(object.mask_metadata_url)
        ? globalThis.String(object.mask_metadata_url)
        : "",
      pieces: globalThis.Array.isArray(object?.pieces)
        ? object.pieces.map((e: any) => PieceState.fromJSON(e))
        : [],
      players: globalThis.Array.isArray(object?.players)
        ? object.players.map((e: any) => PlayerState.fromJSON(e))
        : [],
      locks: globalThis.Array.isArray(object?.locks)
        ? object.locks.map((e: any) => LockState.fromJSON(e))
        : [],
    };
  },

  toJSON(message: RoomStateSnapshot): unknown {
    const obj: any = {};
    if (message.lastEventId !== 0) {
      obj.lastEventId = Math.round(message.lastEventId);
    }
    if (message.gridSize !== 0) {
      obj.gridSize = Math.round(message.gridSize);
    }
    if (message.pieceCount !== 0) {
      obj.pieceCount = Math.round(message.pieceCount);
    }
    if (message.placedPieceCount !== 0) {
      obj.placedPieceCount = Math.round(message.placedPieceCount);
    }
    if (message.completed !== false) {
      obj.completed = message.completed;
    }
    if (message.solveTimeMs !== 0) {
      obj.solveTimeMs = Math.round(message.solveTimeMs);
    }
    if (message.baseImageUrl !== "") {
      obj.baseImageUrl = message.baseImageUrl;
    }
    if (message.maskMetadataUrl !== "") {
      obj.maskMetadataUrl = message.maskMetadataUrl;
    }
    if (message.pieces?.length) {
      obj.pieces = message.pieces.map((e) => PieceState.toJSON(e));
    }
    if (message.players?.length) {
      obj.players = message.players.map((e) => PlayerState.toJSON(e));
    }
    if (message.locks?.length) {
      obj.locks = message.locks.map((e) => LockState.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RoomStateSnapshot>, I>>(base?: I): RoomStateSnapshot {
    return RoomStateSnapshot.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RoomStateSnapshot>, I>>(object: I): RoomStateSnapshot {
    const message = createBaseRoomStateSnapshot();
    message.lastEventId = object.lastEventId ?? 0;
    message.gridSize = object.gridSize ?? 0;
    message.pieceCount = object.pieceCount ?? 0;
    message.placedPieceCount = object.placedPieceCount ?? 0;
    message.completed = object.completed ?? false;
    message.solveTimeMs = object.solveTimeMs ?? 0;
    message.baseImageUrl = object.baseImageUrl ?? "";
    message.maskMetadataUrl = object.maskMetadataUrl ?? "";
    message.pieces = object.pieces?.map((e) => PieceState.fromPartial(e)) || [];
    message.players = object.players?.map((e) => PlayerState.fromPartial(e)) || [];
    message.locks = object.locks?.map((e) => LockState.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGameMessage(): GameMessage {
  return {
    schemaVersion: 0,
    roomId: "",
    eventId: 0,
    serverTime: 0,
    connectIntent: undefined,
    claimPieceIntent: undefined,
    movePieceIntent: undefined,
    releasePieceIntent: undefined,
    heartbeatIntent: undefined,
    reconnectSyncIntent: undefined,
    leaveRoomIntent: undefined,
    pieceLockedEvent: undefined,
    roomMovementTick: undefined,
    piecePlacedEvent: undefined,
    pieceReleasedEvent: undefined,
    playerJoinedEvent: undefined,
    playerLeftEvent: undefined,
    roomCompletedEvent: undefined,
    roomExpiredEvent: undefined,
    roomExpiringSoonEvent: undefined,
    errorEvent: undefined,
    roomStateSnapshot: undefined,
  };
}

export const GameMessage: MessageFns<GameMessage> = {
  encode(message: GameMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.schemaVersion !== 0) {
      writer.uint32(8).uint32(message.schemaVersion);
    }
    if (message.roomId !== "") {
      writer.uint32(18).string(message.roomId);
    }
    if (message.eventId !== 0) {
      writer.uint32(24).uint64(message.eventId);
    }
    if (message.serverTime !== 0) {
      writer.uint32(32).uint64(message.serverTime);
    }
    if (message.connectIntent !== undefined) {
      ConnectIntent.encode(message.connectIntent, writer.uint32(82).fork()).join();
    }
    if (message.claimPieceIntent !== undefined) {
      ClaimPieceIntent.encode(message.claimPieceIntent, writer.uint32(90).fork()).join();
    }
    if (message.movePieceIntent !== undefined) {
      MovePieceIntent.encode(message.movePieceIntent, writer.uint32(98).fork()).join();
    }
    if (message.releasePieceIntent !== undefined) {
      ReleasePieceIntent.encode(message.releasePieceIntent, writer.uint32(106).fork()).join();
    }
    if (message.heartbeatIntent !== undefined) {
      HeartbeatIntent.encode(message.heartbeatIntent, writer.uint32(114).fork()).join();
    }
    if (message.reconnectSyncIntent !== undefined) {
      ReconnectSyncIntent.encode(message.reconnectSyncIntent, writer.uint32(122).fork()).join();
    }
    if (message.leaveRoomIntent !== undefined) {
      LeaveRoomIntent.encode(message.leaveRoomIntent, writer.uint32(130).fork()).join();
    }
    if (message.pieceLockedEvent !== undefined) {
      PieceLockedEvent.encode(message.pieceLockedEvent, writer.uint32(162).fork()).join();
    }
    if (message.roomMovementTick !== undefined) {
      RoomMovementTick.encode(message.roomMovementTick, writer.uint32(170).fork()).join();
    }
    if (message.piecePlacedEvent !== undefined) {
      PiecePlacedEvent.encode(message.piecePlacedEvent, writer.uint32(178).fork()).join();
    }
    if (message.pieceReleasedEvent !== undefined) {
      PieceReleasedEvent.encode(message.pieceReleasedEvent, writer.uint32(186).fork()).join();
    }
    if (message.playerJoinedEvent !== undefined) {
      PlayerJoinedEvent.encode(message.playerJoinedEvent, writer.uint32(194).fork()).join();
    }
    if (message.playerLeftEvent !== undefined) {
      PlayerLeftEvent.encode(message.playerLeftEvent, writer.uint32(202).fork()).join();
    }
    if (message.roomCompletedEvent !== undefined) {
      RoomCompletedEvent.encode(message.roomCompletedEvent, writer.uint32(210).fork()).join();
    }
    if (message.roomExpiredEvent !== undefined) {
      RoomExpiredEvent.encode(message.roomExpiredEvent, writer.uint32(218).fork()).join();
    }
    if (message.roomExpiringSoonEvent !== undefined) {
      RoomExpiringSoonEvent.encode(message.roomExpiringSoonEvent, writer.uint32(242).fork()).join();
    }
    if (message.errorEvent !== undefined) {
      ErrorEvent.encode(message.errorEvent, writer.uint32(226).fork()).join();
    }
    if (message.roomStateSnapshot !== undefined) {
      RoomStateSnapshot.encode(message.roomStateSnapshot, writer.uint32(234).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GameMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGameMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.schemaVersion = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.roomId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.eventId = longToNumber(reader.uint64());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.serverTime = longToNumber(reader.uint64());
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.connectIntent = ConnectIntent.decode(reader, reader.uint32());
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.claimPieceIntent = ClaimPieceIntent.decode(reader, reader.uint32());
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.movePieceIntent = MovePieceIntent.decode(reader, reader.uint32());
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.releasePieceIntent = ReleasePieceIntent.decode(reader, reader.uint32());
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.heartbeatIntent = HeartbeatIntent.decode(reader, reader.uint32());
          continue;
        }
        case 15: {
          if (tag !== 122) {
            break;
          }

          message.reconnectSyncIntent = ReconnectSyncIntent.decode(reader, reader.uint32());
          continue;
        }
        case 16: {
          if (tag !== 130) {
            break;
          }

          message.leaveRoomIntent = LeaveRoomIntent.decode(reader, reader.uint32());
          continue;
        }
        case 20: {
          if (tag !== 162) {
            break;
          }

          message.pieceLockedEvent = PieceLockedEvent.decode(reader, reader.uint32());
          continue;
        }
        case 21: {
          if (tag !== 170) {
            break;
          }

          message.roomMovementTick = RoomMovementTick.decode(reader, reader.uint32());
          continue;
        }
        case 22: {
          if (tag !== 178) {
            break;
          }

          message.piecePlacedEvent = PiecePlacedEvent.decode(reader, reader.uint32());
          continue;
        }
        case 23: {
          if (tag !== 186) {
            break;
          }

          message.pieceReleasedEvent = PieceReleasedEvent.decode(reader, reader.uint32());
          continue;
        }
        case 24: {
          if (tag !== 194) {
            break;
          }

          message.playerJoinedEvent = PlayerJoinedEvent.decode(reader, reader.uint32());
          continue;
        }
        case 25: {
          if (tag !== 202) {
            break;
          }

          message.playerLeftEvent = PlayerLeftEvent.decode(reader, reader.uint32());
          continue;
        }
        case 26: {
          if (tag !== 210) {
            break;
          }

          message.roomCompletedEvent = RoomCompletedEvent.decode(reader, reader.uint32());
          continue;
        }
        case 27: {
          if (tag !== 218) {
            break;
          }

          message.roomExpiredEvent = RoomExpiredEvent.decode(reader, reader.uint32());
          continue;
        }
        case 30: {
          if (tag !== 242) {
            break;
          }

          message.roomExpiringSoonEvent = RoomExpiringSoonEvent.decode(reader, reader.uint32());
          continue;
        }
        case 28: {
          if (tag !== 226) {
            break;
          }

          message.errorEvent = ErrorEvent.decode(reader, reader.uint32());
          continue;
        }
        case 29: {
          if (tag !== 234) {
            break;
          }

          message.roomStateSnapshot = RoomStateSnapshot.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GameMessage {
    return {
      schemaVersion: isSet(object.schemaVersion)
        ? globalThis.Number(object.schemaVersion)
        : isSet(object.schema_version)
        ? globalThis.Number(object.schema_version)
        : 0,
      roomId: isSet(object.roomId)
        ? globalThis.String(object.roomId)
        : isSet(object.room_id)
        ? globalThis.String(object.room_id)
        : "",
      eventId: isSet(object.eventId)
        ? globalThis.Number(object.eventId)
        : isSet(object.event_id)
        ? globalThis.Number(object.event_id)
        : 0,
      serverTime: isSet(object.serverTime)
        ? globalThis.Number(object.serverTime)
        : isSet(object.server_time)
        ? globalThis.Number(object.server_time)
        : 0,
      connectIntent: isSet(object.connectIntent)
        ? ConnectIntent.fromJSON(object.connectIntent)
        : isSet(object.connect_intent)
        ? ConnectIntent.fromJSON(object.connect_intent)
        : undefined,
      claimPieceIntent: isSet(object.claimPieceIntent)
        ? ClaimPieceIntent.fromJSON(object.claimPieceIntent)
        : isSet(object.claim_piece_intent)
        ? ClaimPieceIntent.fromJSON(object.claim_piece_intent)
        : undefined,
      movePieceIntent: isSet(object.movePieceIntent)
        ? MovePieceIntent.fromJSON(object.movePieceIntent)
        : isSet(object.move_piece_intent)
        ? MovePieceIntent.fromJSON(object.move_piece_intent)
        : undefined,
      releasePieceIntent: isSet(object.releasePieceIntent)
        ? ReleasePieceIntent.fromJSON(object.releasePieceIntent)
        : isSet(object.release_piece_intent)
        ? ReleasePieceIntent.fromJSON(object.release_piece_intent)
        : undefined,
      heartbeatIntent: isSet(object.heartbeatIntent)
        ? HeartbeatIntent.fromJSON(object.heartbeatIntent)
        : isSet(object.heartbeat_intent)
        ? HeartbeatIntent.fromJSON(object.heartbeat_intent)
        : undefined,
      reconnectSyncIntent: isSet(object.reconnectSyncIntent)
        ? ReconnectSyncIntent.fromJSON(object.reconnectSyncIntent)
        : isSet(object.reconnect_sync_intent)
        ? ReconnectSyncIntent.fromJSON(object.reconnect_sync_intent)
        : undefined,
      leaveRoomIntent: isSet(object.leaveRoomIntent)
        ? LeaveRoomIntent.fromJSON(object.leaveRoomIntent)
        : isSet(object.leave_room_intent)
        ? LeaveRoomIntent.fromJSON(object.leave_room_intent)
        : undefined,
      pieceLockedEvent: isSet(object.pieceLockedEvent)
        ? PieceLockedEvent.fromJSON(object.pieceLockedEvent)
        : isSet(object.piece_locked_event)
        ? PieceLockedEvent.fromJSON(object.piece_locked_event)
        : undefined,
      roomMovementTick: isSet(object.roomMovementTick)
        ? RoomMovementTick.fromJSON(object.roomMovementTick)
        : isSet(object.room_movement_tick)
        ? RoomMovementTick.fromJSON(object.room_movement_tick)
        : undefined,
      piecePlacedEvent: isSet(object.piecePlacedEvent)
        ? PiecePlacedEvent.fromJSON(object.piecePlacedEvent)
        : isSet(object.piece_placed_event)
        ? PiecePlacedEvent.fromJSON(object.piece_placed_event)
        : undefined,
      pieceReleasedEvent: isSet(object.pieceReleasedEvent)
        ? PieceReleasedEvent.fromJSON(object.pieceReleasedEvent)
        : isSet(object.piece_released_event)
        ? PieceReleasedEvent.fromJSON(object.piece_released_event)
        : undefined,
      playerJoinedEvent: isSet(object.playerJoinedEvent)
        ? PlayerJoinedEvent.fromJSON(object.playerJoinedEvent)
        : isSet(object.player_joined_event)
        ? PlayerJoinedEvent.fromJSON(object.player_joined_event)
        : undefined,
      playerLeftEvent: isSet(object.playerLeftEvent)
        ? PlayerLeftEvent.fromJSON(object.playerLeftEvent)
        : isSet(object.player_left_event)
        ? PlayerLeftEvent.fromJSON(object.player_left_event)
        : undefined,
      roomCompletedEvent: isSet(object.roomCompletedEvent)
        ? RoomCompletedEvent.fromJSON(object.roomCompletedEvent)
        : isSet(object.room_completed_event)
        ? RoomCompletedEvent.fromJSON(object.room_completed_event)
        : undefined,
      roomExpiredEvent: isSet(object.roomExpiredEvent)
        ? RoomExpiredEvent.fromJSON(object.roomExpiredEvent)
        : isSet(object.room_expired_event)
        ? RoomExpiredEvent.fromJSON(object.room_expired_event)
        : undefined,
      roomExpiringSoonEvent: isSet(object.roomExpiringSoonEvent)
        ? RoomExpiringSoonEvent.fromJSON(object.roomExpiringSoonEvent)
        : isSet(object.room_expiring_soon_event)
        ? RoomExpiringSoonEvent.fromJSON(object.room_expiring_soon_event)
        : undefined,
      errorEvent: isSet(object.errorEvent)
        ? ErrorEvent.fromJSON(object.errorEvent)
        : isSet(object.error_event)
        ? ErrorEvent.fromJSON(object.error_event)
        : undefined,
      roomStateSnapshot: isSet(object.roomStateSnapshot)
        ? RoomStateSnapshot.fromJSON(object.roomStateSnapshot)
        : isSet(object.room_state_snapshot)
        ? RoomStateSnapshot.fromJSON(object.room_state_snapshot)
        : undefined,
    };
  },

  toJSON(message: GameMessage): unknown {
    const obj: any = {};
    if (message.schemaVersion !== 0) {
      obj.schemaVersion = Math.round(message.schemaVersion);
    }
    if (message.roomId !== "") {
      obj.roomId = message.roomId;
    }
    if (message.eventId !== 0) {
      obj.eventId = Math.round(message.eventId);
    }
    if (message.serverTime !== 0) {
      obj.serverTime = Math.round(message.serverTime);
    }
    if (message.connectIntent !== undefined) {
      obj.connectIntent = ConnectIntent.toJSON(message.connectIntent);
    }
    if (message.claimPieceIntent !== undefined) {
      obj.claimPieceIntent = ClaimPieceIntent.toJSON(message.claimPieceIntent);
    }
    if (message.movePieceIntent !== undefined) {
      obj.movePieceIntent = MovePieceIntent.toJSON(message.movePieceIntent);
    }
    if (message.releasePieceIntent !== undefined) {
      obj.releasePieceIntent = ReleasePieceIntent.toJSON(message.releasePieceIntent);
    }
    if (message.heartbeatIntent !== undefined) {
      obj.heartbeatIntent = HeartbeatIntent.toJSON(message.heartbeatIntent);
    }
    if (message.reconnectSyncIntent !== undefined) {
      obj.reconnectSyncIntent = ReconnectSyncIntent.toJSON(message.reconnectSyncIntent);
    }
    if (message.leaveRoomIntent !== undefined) {
      obj.leaveRoomIntent = LeaveRoomIntent.toJSON(message.leaveRoomIntent);
    }
    if (message.pieceLockedEvent !== undefined) {
      obj.pieceLockedEvent = PieceLockedEvent.toJSON(message.pieceLockedEvent);
    }
    if (message.roomMovementTick !== undefined) {
      obj.roomMovementTick = RoomMovementTick.toJSON(message.roomMovementTick);
    }
    if (message.piecePlacedEvent !== undefined) {
      obj.piecePlacedEvent = PiecePlacedEvent.toJSON(message.piecePlacedEvent);
    }
    if (message.pieceReleasedEvent !== undefined) {
      obj.pieceReleasedEvent = PieceReleasedEvent.toJSON(message.pieceReleasedEvent);
    }
    if (message.playerJoinedEvent !== undefined) {
      obj.playerJoinedEvent = PlayerJoinedEvent.toJSON(message.playerJoinedEvent);
    }
    if (message.playerLeftEvent !== undefined) {
      obj.playerLeftEvent = PlayerLeftEvent.toJSON(message.playerLeftEvent);
    }
    if (message.roomCompletedEvent !== undefined) {
      obj.roomCompletedEvent = RoomCompletedEvent.toJSON(message.roomCompletedEvent);
    }
    if (message.roomExpiredEvent !== undefined) {
      obj.roomExpiredEvent = RoomExpiredEvent.toJSON(message.roomExpiredEvent);
    }
    if (message.roomExpiringSoonEvent !== undefined) {
      obj.roomExpiringSoonEvent = RoomExpiringSoonEvent.toJSON(message.roomExpiringSoonEvent);
    }
    if (message.errorEvent !== undefined) {
      obj.errorEvent = ErrorEvent.toJSON(message.errorEvent);
    }
    if (message.roomStateSnapshot !== undefined) {
      obj.roomStateSnapshot = RoomStateSnapshot.toJSON(message.roomStateSnapshot);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GameMessage>, I>>(base?: I): GameMessage {
    return GameMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GameMessage>, I>>(object: I): GameMessage {
    const message = createBaseGameMessage();
    message.schemaVersion = object.schemaVersion ?? 0;
    message.roomId = object.roomId ?? "";
    message.eventId = object.eventId ?? 0;
    message.serverTime = object.serverTime ?? 0;
    message.connectIntent = (object.connectIntent !== undefined && object.connectIntent !== null)
      ? ConnectIntent.fromPartial(object.connectIntent)
      : undefined;
    message.claimPieceIntent = (object.claimPieceIntent !== undefined && object.claimPieceIntent !== null)
      ? ClaimPieceIntent.fromPartial(object.claimPieceIntent)
      : undefined;
    message.movePieceIntent = (object.movePieceIntent !== undefined && object.movePieceIntent !== null)
      ? MovePieceIntent.fromPartial(object.movePieceIntent)
      : undefined;
    message.releasePieceIntent = (object.releasePieceIntent !== undefined && object.releasePieceIntent !== null)
      ? ReleasePieceIntent.fromPartial(object.releasePieceIntent)
      : undefined;
    message.heartbeatIntent = (object.heartbeatIntent !== undefined && object.heartbeatIntent !== null)
      ? HeartbeatIntent.fromPartial(object.heartbeatIntent)
      : undefined;
    message.reconnectSyncIntent = (object.reconnectSyncIntent !== undefined && object.reconnectSyncIntent !== null)
      ? ReconnectSyncIntent.fromPartial(object.reconnectSyncIntent)
      : undefined;
    message.leaveRoomIntent = (object.leaveRoomIntent !== undefined && object.leaveRoomIntent !== null)
      ? LeaveRoomIntent.fromPartial(object.leaveRoomIntent)
      : undefined;
    message.pieceLockedEvent = (object.pieceLockedEvent !== undefined && object.pieceLockedEvent !== null)
      ? PieceLockedEvent.fromPartial(object.pieceLockedEvent)
      : undefined;
    message.roomMovementTick = (object.roomMovementTick !== undefined && object.roomMovementTick !== null)
      ? RoomMovementTick.fromPartial(object.roomMovementTick)
      : undefined;
    message.piecePlacedEvent = (object.piecePlacedEvent !== undefined && object.piecePlacedEvent !== null)
      ? PiecePlacedEvent.fromPartial(object.piecePlacedEvent)
      : undefined;
    message.pieceReleasedEvent = (object.pieceReleasedEvent !== undefined && object.pieceReleasedEvent !== null)
      ? PieceReleasedEvent.fromPartial(object.pieceReleasedEvent)
      : undefined;
    message.playerJoinedEvent = (object.playerJoinedEvent !== undefined && object.playerJoinedEvent !== null)
      ? PlayerJoinedEvent.fromPartial(object.playerJoinedEvent)
      : undefined;
    message.playerLeftEvent = (object.playerLeftEvent !== undefined && object.playerLeftEvent !== null)
      ? PlayerLeftEvent.fromPartial(object.playerLeftEvent)
      : undefined;
    message.roomCompletedEvent = (object.roomCompletedEvent !== undefined && object.roomCompletedEvent !== null)
      ? RoomCompletedEvent.fromPartial(object.roomCompletedEvent)
      : undefined;
    message.roomExpiredEvent = (object.roomExpiredEvent !== undefined && object.roomExpiredEvent !== null)
      ? RoomExpiredEvent.fromPartial(object.roomExpiredEvent)
      : undefined;
    message.roomExpiringSoonEvent =
      (object.roomExpiringSoonEvent !== undefined && object.roomExpiringSoonEvent !== null)
        ? RoomExpiringSoonEvent.fromPartial(object.roomExpiringSoonEvent)
        : undefined;
    message.errorEvent = (object.errorEvent !== undefined && object.errorEvent !== null)
      ? ErrorEvent.fromPartial(object.errorEvent)
      : undefined;
    message.roomStateSnapshot = (object.roomStateSnapshot !== undefined && object.roomStateSnapshot !== null)
      ? RoomStateSnapshot.fromPartial(object.roomStateSnapshot)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
